"""fix: Rename profissionais.registro_profissional to registro_professional

Revision ID: 9a4b4ae105b3
Revises: 20260108_0003
Create Date: 2026-01-21 13:48:34.949857

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a4b4ae105b3'
down_revision = '20260108_0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profissionais', 'registro_profissional', new_column_name='registro_professional',
               existing_type=sa.String(50),
               existing_nullable=False,
               existing_unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profissionais', 'registro_professional', new_column_name='registro_profissional',
               existing_type=sa.String(50),
               existing_nullable=False,
               existing_unique=True)
    # ### end Alembic commands ###
